version: '3.3'
services:
  nodejs:
    image: node:12-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - sh
    command:
      - -c
      - |
        yarn && yarn db:migrate && yarn build && ls ./dist/src && yarn start
    ports:
      - 5009:4000
    restart: always
    expose: ["4000"]
    networks:
      - docker-network
    environment:
      VIRTUAL_PORT: 5009
      VIRTUAL_HOST: "postfyapi.soshiharami.com"
      LETSENCRYPT_HOST: "postfyapi.soshiharami.com"
      LETSENCRYPT_EMAIL: "soshi0807sss@gmail.com"


networks:
  docker-network:
    external: true
