version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-net


  nodejs:
    image: node:15.13.0-alpine
    volumes:
      - .:/app:cached
    working_dir: /app
    entrypoint:
      - sh
    command:
      - -c
      - |
        yarn && yarn db:migrate:prod && yarn build && yarn start
    ports:
      - "4000:4000"
    networks:
      - app-net
volumes:
  postgres:

networks:
  app-net:
    driver: bridge
